- name: read secrets
  become: false
  local_action: |
    shell ssh {{secret_user}}@{{secret_server}} cat {{secret_path}}/{{item.src}}
  register: read_secrets
  with_items: "{{secret_vars}}"

- name: assign secrets to facts
  set_fact: "{{item.item.dest}}=\"{{item.stdout}}\""
  with_items: "{{read_secrets.results}}"
  no_log: true
